# Generated by Django 5.0.3 on 2024-05-17 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionministere', '0007_alter_etablissement_poste_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('etablissement_poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestionministere.etablissement_poste')),
            ],
            options={
                'verbose_name': 'Nomination',
                'verbose_name_plural': 'Gestion des Nominations',
            },
            bases=('gestionministere.etablissement_poste',),
        ),
    ]
