# Generated by Django 5.0.3 on 2024-05-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nomination',
        ),
    ]
