# Generated by Django 5.0.3 on 2024-05-15 20:44

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('anciennete_min', models.IntegerField(blank=True, default=1, null=True, verbose_name='Ancienneté min')),
            ],
            options={
                'verbose_name': 'Poste administratif',
                'verbose_name_plural': 'Postes',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('BP', models.CharField(blank=True, max_length=64, null=True, verbose_name='BP')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='email')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionministere.departement', verbose_name='Departement')),
            ],
            options={
                'verbose_name': 'Etablissement',
                'verbose_name_plural': 'Etablissements',
            },
        ),
        migrations.CreateModel(
            name='Etablissement_Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionministere.etablissement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionministere.poste')),
            ],
        ),
        migrations.AddField(
            model_name='etablissement',
            name='poste',
            field=models.ManyToManyField(through='gestionministere.Etablissement_Poste', to='gestionministere.poste'),
        ),
        migrations.CreateModel(
            name='Carriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeArrive', models.DateField(blank=True, null=True, verbose_name="Année d'entrée")),
                ('anneeDepart', models.DateField(blank=True, null=True, verbose_name='Année de sortie')),
                ('performance', models.CharField(max_length=64, verbose_name='Performance')),
                ('discipline', models.TextField(max_length=64, verbose_name='Discipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionministere.etablissement')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionministere.poste')),
            ],
            options={
                'verbose_name': 'Carriere',
                'verbose_name_plural': 'Carrieres',
            },
        ),
        migrations.CreateModel(
            name='ProfilEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='enseignant_cvs/', verbose_name='CV')),
                ('dateNaissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('anneeSortie', models.DateField(verbose_name='Année de sortie')),
                ('matricule', models.CharField(max_length=64, unique=True, verbose_name='Matricule')),
                ('situationMatrimoniale', models.CharField(max_length=64, verbose_name='Situation Matrimoniale')),
                ('categorie', models.CharField(max_length=64, verbose_name='Categorie')),
                ('departementOrigine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionministere.departement')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionministere.etablissement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Enseignant',
                'verbose_name_plural': 'Profils Enseignant',
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionministere.region'),
        ),
    ]
