# Generated by Django 5.0.3 on 2024-05-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionministere', '0002_matiere_profilenseignant_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenseignant',
            name='sexe',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='profilenseignant',
            name='telephone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Numéro de télephone'),
        ),
    ]
