# Generated by Django 5.0.3 on 2024-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionministere', '0004_alter_carriere_discipline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenseignant',
            name='avancement',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Avancement'),
        ),
    ]
