# Generated by Django 5.0.3 on 2024-05-22 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionministere', '0007_alter_etablissement_poste_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenseignant',
            name='dernierAnneeVerif',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='DerniereAnnee'),
        ),
        migrations.AlterField(
            model_name='etablissement_poste',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enseignant éligible'),
        ),
    ]
